package postgres

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/paula-dot/kenya-admin-boundaries-api/internal/domain"
)

// CountyRepo implements the service.CountyRepository interface.
type CountyRepo struct {
	// Querier is the interface generated by sqlc.
	// Using the interface rather than the concrete *Queries struct makes unit testing easier.
	db Querier
}

// NewCountyRepository creates a new PostgreSQL-backed county repository.
func NewCountyRepository(pool *pgxpool.Pool) *CountyRepo {
	return &CountyRepo{
		// New() is auto-generated by sqlc to wrap the connection pool
		db: New(pool),
	}
}

// GetCountyByCode executes the SQL query and maps the result to the domain model.
func (r *CountyRepo) GetCountyByCode(ctx context.Context, code string) (*domain.County, error) {
	// Call the sqlc-generated GetCountyByCode method
	row, err := r.db.GetCountyByCode(ctx, code)
	if err != nil {
		return nil, fmt.Errorf("repository - GetCountyByCode failed: %w", err)
	}

	// code is now a plain string per sqlc (not a sql.NullString)
	cCode := ""
	if row.Code != "" {
		cCode = row.Code
	}

	// created_at is no longer returned by the query; use zero value
	created := time.Time{}

	// Try to parse code into an integer ID if numeric
	var idVal int32 = 0
	if parsed, err := strconv.Atoi(cCode); err == nil {
		idVal = int32(parsed)
	}

	// Map the database-specific struct to your pure domain model
	county := &domain.County{
		ID:        idVal,
		Code:      cCode,
		Name:      row.Name,
		Geometry:  row.Geojson,
		CreatedAt: created,
	}

	return county, nil
}

// ListCounties executes the list query and maps the slice of results to domain models.
func (r *CountyRepo) ListCounties(ctx context.Context) ([]*domain.County, error) {
	rows, err := r.db.ListCounties(ctx)
	if err != nil {
		return nil, fmt.Errorf("repository - ListCounties failed: %w", err)
	}

	var counties []*domain.County
	for _, row := range rows {
		code := ""
		// sqlc now aliases the column as `id` -> struct field `ID`
		if row.ID != "" {
			code = row.ID
		}

		// Try to parse the official county code into an integer to use as the ID
		var idVal int32 = 0
		if parsed, err := strconv.Atoi(code); err == nil {
			idVal = int32(parsed)
		}

		c := &domain.County{
			ID:       idVal,
			Code:     code,
			Name:     row.Name,
			Geometry: row.Geojson,
		}
		counties = append(counties, c)
	}

	return counties, nil
}

// GetCountyMetadata retrieves lightweight county metadata without geometries.
func (r *CountyRepo) GetCountyMetadata(ctx context.Context, code string) (GetCountyMetadataRow, error) {
	return r.db.GetCountyMetadata(ctx, code)
}
