// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

type Constituency struct {
	ConstituencyCode string      `json:"constituency_code"`
	ConstituencyName string      `json:"constituency_name"`
	CountyCode       string      `json:"county_code"`
	Geom             interface{} `json:"geom"`
}

type County struct {
	CountyCode string      `json:"county_code"`
	CountyName string      `json:"county_name"`
	Geom       interface{} `json:"geom"`
}

type SubCounty struct {
	CountyCode    string `json:"county_code"`
	CountyName    string `json:"county_name"`
	SubCountyCode string `json:"sub_county_code"`
	SubCountyName string `json:"sub_county_name"`
}

type Ward struct {
	CountyCode       int32  `json:"county_code"`
	CountyName       string `json:"county_name"`
	ConstituencyCode int32  `json:"constituency_code"`
	ConstituencyName string `json:"constituency_name"`
	WardCode         int32  `json:"ward_code"`
	WardName         string `json:"ward_name"`
}
