// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	// Inserts a new county and converts the incoming GeoJSON payload into a PostGIS geometry.
	CreateCounty(ctx context.Context, arg CreateCountyParams) (CreateCountyRow, error)
	// Fetches a specific county and automatically formats the geometry as valid GeoJSON.
	GetCountyByID(ctx context.Context, id int32) (GetCountyByIDRow, error)
	// Retrieves a list of all counties.
	ListCounties(ctx context.Context) ([]ListCountiesRow, error)
}

var _ Querier = (*Queries)(nil)
