// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounty = `-- name: CreateCounty :one
INSERT INTO counties (code, name, geom)
VALUES (
        $1,
        $2,
        ST_Multi(ST_GeomFromGeoJSON($3::text))
       )
RETURNING id, code, name, created_at
`

type CreateCountyParams struct {
	Code    pgtype.Text `json:"code"`
	Name    string      `json:"name"`
	Column3 string      `json:"column_3"`
}

type CreateCountyRow struct {
	ID        int32              `json:"id"`
	Code      pgtype.Text        `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Inserts a new county and converts the incoming GeoJSON payload into a PostGIS geometry.
func (q *Queries) CreateCounty(ctx context.Context, arg CreateCountyParams) (CreateCountyRow, error) {
	row := q.db.QueryRow(ctx, createCounty, arg.Code, arg.Name, arg.Column3)
	var i CreateCountyRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCountyByID = `-- name: GetCountyByID :one
SELECT
    id,
    code,
    name,
    ST_AsGeoJSON(geom)::jsonb AS geojson,
    created_at
FROM counties
WHERE id = $1
LIMIT 1
`

type GetCountyByIDRow struct {
	ID        int32              `json:"id"`
	Code      pgtype.Text        `json:"code"`
	Name      string             `json:"name"`
	Geojson   []byte             `json:"geojson"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Fetches a specific county and automatically formats the geometry as valid GeoJSON.
func (q *Queries) GetCountyByID(ctx context.Context, id int32) (GetCountyByIDRow, error) {
	row := q.db.QueryRow(ctx, getCountyByID, id)
	var i GetCountyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Geojson,
		&i.CreatedAt,
	)
	return i, err
}

const listCounties = `-- name: ListCounties :many
SELECT
    id,
    code,
    name,
    ST_AsGeoJSON(geom)::jsonb AS geojson
FROM counties
ORDER BY name
`

type ListCountiesRow struct {
	ID      int32       `json:"id"`
	Code    pgtype.Text `json:"code"`
	Name    string      `json:"name"`
	Geojson []byte      `json:"geojson"`
}

// Retrieves a list of all counties.
func (q *Queries) ListCounties(ctx context.Context) ([]ListCountiesRow, error) {
	rows, err := q.db.Query(ctx, listCounties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountiesRow{}
	for rows.Next() {
		var i ListCountiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Geojson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
