// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	// Inserts a new constituency and converts the incoming GeoJSON payload into a PostGIS geometry.
	CreateConstituency(ctx context.Context, arg CreateConstituencyParams) (CreateConstituencyRow, error)
	// Inserts a new county and converts the incoming GeoJSON payload into a PostGIS geometry.
	CreateCounty(ctx context.Context, arg CreateCountyParams) (CreateCountyRow, error)
	GetAllSubCounties(ctx context.Context) ([]SubCounty, error)
	// Fetches a specific constituency by its official code.
	GetConstituencyByCode(ctx context.Context, constituencyCode string) (GetConstituencyByCodeRow, error)
	// Fetches a specific county by its official code and automatically formats the geometry as valid GeoJSON.
	GetCountyByCode(ctx context.Context, countyCode string) (GetCountyByCodeRow, error)
	// Retrieves just the code and name of a county without the geometry
	GetCountyMetadata(ctx context.Context, countyCode string) (GetCountyMetadataRow, error)
	GetIntersectingBoundary(ctx context.Context, arg GetIntersectingBoundaryParams) (GetIntersectingBoundaryRow, error)
	GetSubCountiesByCounty(ctx context.Context, countyCode string) ([]GetSubCountiesByCountyRow, error)
	// Retrieves a list of all constituencies.
	ListConstituencies(ctx context.Context) ([]ListConstituenciesRow, error)
	// Retrieves all constituencies belonging to a specific county (Perfect for your nested route!)
	ListConstituenciesByCounty(ctx context.Context, countyCode string) ([]ListConstituenciesByCountyRow, error)
	// Retrieves lightweight list of constituencies (code and name) for a county
	ListConstituenciesMetadataByCounty(ctx context.Context, countyCode string) ([]ListConstituenciesMetadataByCountyRow, error)
	// Retrieves a list of all counties. Uses code/name and numeric ordering.
	ListCounties(ctx context.Context) ([]ListCountiesRow, error)
}

var _ Querier = (*Queries)(nil)
